version: "2"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR2"
exclude_patterns:
  - "tests/"
  - "vendor/"
  - "storage/"
  - "routes/"
  - "resources/"
  - "public/"
  - "node_modules/"
  - "database/"
  - "config/"
  - "bootstrap/"
  - "_ide_helper.php"
  - ".phpstorm.meta.php"
  - "dcat_admin_ide_helper.php"
